apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-pmix

commonLabels:
  hpcjob: test-kubectl

replicas:
- count: 5
  name: hpc-cn

images:
- name: k8s-compute
  newName: quay.io/my-user/k8s-mpi-with-runtime
  newTag: latest
- name: k8s-login
  newName: quay.io/my-user/k8s-mpi-with-runtime
  newTag: latest
- name: k8s-runtime
  newName: quay.io/my-user/k8s-runtime
  newTag: latest
- name: k8s-waitfor
  newName: quay.io/my-user/k8s-waitfor
  newTag: latest

resources:
- ../base
- ../rbac

patches:
- patch: |-
    kind: StatefulSet
    metadata:
      name: hpc-cn
    spec:
      template:
        spec:
          containers:
            - name: k8s-compute
              env:
              - name: OMPI_MCA_plm_rsh_agent
                value: /opt/k8s/bin/kubexec.sh
              - name: PRTE_MCA_plm_rsh_agent
                value: /opt/k8s/bin/kubexec.sh
  target:
    kind: StatefulSet
    name: hpc-cn
- patch: |-
    kind: Job
    metadata:
      name: hpc-cluster-login
    spec:
      template:
        spec:
          containers:
            - name: login
              env:
              - name: OMPI_MCA_plm_rsh_agent
                value: /opt/k8s/bin/kubexec.sh
              - name: PRTE_MCA_plm_rsh_agent
                value: /opt/k8s/bin/kubexec.sh
  target:
    kind: Job
    name: hpc-cluster-login

# Some replacements for consistency across the profiles
replacements:
- path: ../replacements/replace-namespace.yaml
- path: ../replacements/replace-service.yaml
- path: ../replacements/replace-cn.yaml
- path: ../replacements/replace-label.yaml
- path: ../replacements/replace-size.yaml
