apiVersion: batch/v1
kind: Job
metadata:
  name: hpc-cluster-login
spec:
  # Number of retries before marking the job as failed
  backoffLimit: 4
  completions: 1
  # Pod template
  template:
    metadata:
      labels:
        # 'app' must match the selector above
        app: hpc-compute-nodes
        hpcnode: login-node
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: DoesNotExist
      serviceAccount: pmix-user
      securityContext:
        runAsUser: 998
        runAsGroup: 995
        fsGroup: 995
      dnsConfig:
        searches:
          -  SERVICE_NAME.NAMESPACE
      # If the container fails then do not try to restart it
      restartPolicy: OnFailure
      initContainers:
      - name: job-waiter
        imagePullPolicy: Always
        image: k8s-waitfor
        command:
        - "timeout"
        args:
        - "120"
        - "/opt/k8s/bin/k8s-wait-for-pods.sh"
        - "NUM_REPLICAS"
        - "NAMESPACE"
        - "hpcnode=compute-node,hpcjob=COMMONLABEL"
        - "SERVICE_NAME"
        - "COMPUTE_NODE_NAME"
        - "/opt/hpc/etc/hostfile"
        - "/opt/hpc/etc/hostfile_ip"
        volumeMounts:
        - name: mpi-hostfile
          mountPath: /opt/hpc/etc
      containers:
      - name: login
        resources:
          requests:
            cpu: 1
        imagePullPolicy: Always
        image: k8s-login
        # Use 'pause' for now while we are debugging things
        command: 
        - "/opt/k8s/bin/pause"
        # Ideally it would just kick off the PRTE daemon and exit when it exits
        #command: ["prte"]
        workingDir: /home/mpiuser
        # Where to place volume mounts inside the container
        volumeMounts:
        - name: mpi-hostfile
          mountPath: /opt/hpc/etc
        - name: dev-shm
          mountPath: /dev/shm
        # Environment variables
        env:
        - name: SHELL
          value: /bin/bash
        - name: OMPI_MCA_orte_default_hostfile
          value: /opt/hpc/etc/hostfile
        - name: PRTE_MCA_prte_default_hostfile
          value: /opt/hpc/etc/hostfile
      # Volumes to make available to the container
      volumes:
      # Shared memory segment is too small by default so replace it
      # https://github.com/kubernetes/kubernetes/issues/28272
      # https://pradiptabanerjee.medium.com/how-to-size-a-memory-backed-kubernetes-emptydir-volume-cdfe39d1b7e5
      - name: dev-shm
        emptyDir:
          medium: Memory
          sizeLimit: 1Gi
      # Volume sharing between initContainer and others in job
      # https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-initialization/#create-a-pod-that-has-an-init-container
      - name: mpi-hostfile
        emptyDir: {}
