kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
  namespace: kube-pmix
roleRef:
  kind: ClusterRole
  name: hpc-service-exec
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: pmix-user
  namespace: kube-pmix
